# Generated by Django 3.0.8 on 2020-08-04 20:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_bloglistingpage_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloglistingpage',
            name='date',
        ),
        migrations.AddField(
            model_name='blogdetailpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
