# Generated by Django 3.0.8 on 2020-08-04 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0005_auto_20200729_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='flexpage',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
